### ISSUE TITLE
❓ How to use v1 models?

### ISSUE THREAD

**Issue by nikich340** [snakers4/silero-models#109]
While v2 models are working fine with given standalone code example, v1 produces errors while loading:
```
Traceback (most recent call last):
  File "C:\Users\NORDLING\.cache\torch\hub\snakers4_silero-models_master\inference.py", line 12, in <module>
    model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
  File "C:\Users\NORDLING\AppData\Roaming\Python\Python39\site-packages\torch\package\package_importer.py", line 84, in __init__
    self.extern_modules = self._read_extern()
  File "C:\Users\NORDLING\AppData\Roaming\Python\Python39\site-packages\torch\package\package_importer.py", line 289, in _read_extern
    self.zip_reader.get_record(".data/extern_modules")
RuntimeError: PytorchStreamReader failed locating file .data/extern_modules: file not found
```

Is there any example how to work with them to generate wav's for test/comparsion?

**Comment by snakers4** [comment]
V1 models have a separate section in the examples notebook:

![image](https://user-images.githubusercontent.com/12515440/142409922-10b887bc-7122-4df4-b60b-5ee9cb41305a.png)
