### ISSUE TITLE
RuntimeError: Unknown qengine

### ISSUE THREAD

**Issue by zoldaten** [snakers4/silero-models#142]
tried to run on orange pi 4B ubuntu 18.04 bionic.
Linux orangepi4 4.4.179-rk3399 #2 SMP Thu May 6 10:53:22 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

built everything correctly.
torch==1.10.0
onnx==1.11.0

 but have problem with  pickle:
```
Traceback (most recent call last):
  File "/home/orangepi/Desktop/speech/tts/example5.py", line 13, in <module>
    model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
  File "/home/orangepi/.local/lib/python3.6/site-packages/torch/package/package_importer.py", line 249, in load_pickle
    result = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1091, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/home/orangepi/.local/lib/python3.6/site-packages/torch/package/package_importer.py", line 227, in persistent_load
    loaded_reduces[reduce_id] = func(self, *args)
  File "/home/orangepi/.local/lib/python3.6/site-packages/torch/jit/_script.py", line 349, in unpackage_script_module
    script_module_id,
RuntimeError: Unknown qengine
```

tried this example:
```
# V3
import os
import torch

device = torch.device('cpu')
torch.set_num_threads(4)
local_file = 'model.pt'

if not os.path.isfile(local_file):
    torch.hub.download_url_to_file('https://models.silero.ai/models/tts/ru/ru_v3.pt',
                                   local_file)  
model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
model.to(device)

example_text = 'В недрах тундры выдры в г+етрах т+ырят в вёдра ядра кедров.'
sample_rate = 48000
speaker='baya'

audio_paths = model.save_wav(text=example_text,
                             speaker=speaker,
                             sample_rate=sample_rate)
```

i tried replace standard pickle like that:
```
pip install pickle5
import pickle5 as pickle
```

but no result (

**Comment by snakers4** [comment]
Hi,

This package contains some quantized models (accentor), that do not run without AVX2 instructions (because they are quantized).

Sometimes [this](https://github.com/snakers4/silero-models/discussions/104) helps

We did not target AMD builds explicitly (yet). Maybe in future with ONNX it will be much easier.
