### ISSUE TITLE
RuntimeError: Unknown type name 'NoneType'

### ISSUE THREAD

**Issue by buildist** [snakers4/silero-models#177]
I get this error when trying the example Pytorch code:

```
Downloading: "https://github.com/snakers4/silero-models/archive/master.zip" to /home/jacob/.cache/torch/hub/master.zip
100.0%
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "/home/jacob/.local/lib/python3.8/site-packages/torch/hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/jacob/.local/lib/python3.8/site-packages/torch/hub.py", line 368, in _load_local
    model = entry(*args, **kwargs)
  File "/home/jacob/.cache/torch/hub/snakers4_silero-models_master/src/silero/silero.py", line 33, in silero_stt
    model, decoder = init_jit_model(model_url=models.stt_models.get(language).get(version).get(jit_model),
  File "/home/jacob/.cache/torch/hub/snakers4_silero-models_master/src/silero/utils.py", line 130, in init_jit_model
    model = torch.jit.load(model_path, map_location=device)
  File "/home/jacob/.local/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError:
Unknown type name 'NoneType':
Serialized   File "code/__torch__/torch/nn/modules/activation.py", line 5
  __buffers__ = []
  training : bool
  _is_full_backward_hook : NoneType
                           ~~~~~~~~ <--- HERE
  dim : Final[int] = 2
  def forward(self: __torch__.torch.nn.modules.activation.Softmax,
```
Python 3.8, Pytorch 1.8.1, CUDA 10.2. I tried both Windows 10 and WSL2 with Ubuntu 20.04, have never seen this error with other projects.

**Comment by snakers4** [comment]
Which model?
In any case most of our models work fine with 1.10 / 1.11.
