### ISSUE TITLE
Getting a ConfigKeyError/ConfigAttributeError/Missing key error following the Tensorflow example.

### ISSUE THREAD

**Issue by Richard929292** [snakers4/silero-models#95]
Following the example given for the tensorflow version and running the code is giving an error (the asterisks just not showing my Username for my computer, lol) I'm struggling a bit with. Sorry if this is a really stupid question, but what should I do to try to solve this? I have not downloaded all of the silero-sst models to my computer if that is the issue.

```
torch.hub.download_url_to_file(models.stt_models.en.latest.tf, 'tf_model.tar.gz')
Traceback (most recent call last):

  File "<ipython-input-19-8fbcbe869937>", line 1, in <module>
    torch.hub.download_url_to_file(models.stt_models.en.latest.tf, 'tf_model.tar.gz')

  File "***\anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 353, in __getattr__
    self._format_and_raise(

  File "***\anaconda3\lib\site-packages\omegaconf\base.py", line 190, in _format_and_raise
    format_and_raise(

  File "***\anaconda3\lib\site-packages\omegaconf\_utils.py", line 821, in format_and_raise
    _raise(ex, cause)

  File "***\anaconda3\lib\site-packages\omegaconf\_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace

  File "***\anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)

  File "***\anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)

  File "***\anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")

ConfigAttributeError: Missing key tf
    full_key: stt_models.en.latest.tf
    object_type=dict
```

**Comment by snakers4** [comment]
Hi, we decided not to support the tf models.
The error obviously says that there is no tf model in the latest models.
See the models.yml file for details - https://github.com/snakers4/silero-models/blob/master/models.yml#L47-L54
